### PR TITLE
Query error coverage

### LINKED ISSUE #593: Uncaught query error
Try searching using a type that doesn't exist:

```python
plants = client.query_document({ '@type' : 'NuclearPowerPlant' })
```
Then you'll get a stack trace

```javascript
{
    "api:message": "Error: query_error(type_not_found(\"NuclearPowerPlant\"))\n  [40] throw(error(query_error(...),_6878))\n  [38] 'document/query':expand_query_document_(transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:\"capacity_factors\",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},'http://lib.terminusdb.com/nuclear#NuclearPowerPlant',_7008{'@type':\"NuclearPowerPlant\"},_6924) at /app/terminusdb/src/core/document/query.pl:147\n  [36] 'document/query':match_query_document_uri(transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:\"capacity_factors\",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},_7050,_7008{'@type':\"NuclearPowerPlant\"},_7054) at /app/terminusdb/src/core/document/query.pl:215\n  [35] solution_sequences:offset(0,api_document:match_query_document_uri(...,_7192,...,_7196)) at /usr/lib/swipl/library/solution_sequences.pl:241\n  [33] api_document:api_generate_documents_by_query('<garbage_collected>','User/auth0%7C613b70276972a400703b8078','TerminatorsX/nuclear/local/branch/capacity_factors',instance,true,true,_7244,_7008{'@type':\"NuclearPowerPlant\"},0,unlimited,_7252) at /app/terminusdb/src/core/api/api_document.pl:123\n  [32] '$apply':forall('<garbage_collected>',routes:json_write_with_header(...,_7310,...,false,...)) at /usr/lib/swipl/boot/apply.pl:52\n  [31] '<meta-call>'('<garbage_collected>') <foreign>\n  [30] catch(routes:(...,...),error(query_error(...),context(_7410,_7412)),routes:do_or_die(...,...)) at /usr/lib/swipl/boot/init.pl:532\n  [29] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:582\n\nNote: some frames are missing due to last-call optimization.\nRe-run your program in debug mode (:- debug.) to get more detail.\n\n",
    "api:status": "api:server_error"
}
```

### PR DESCRIPTION
**Pull request by GavinMendelGleason**
Should close #593

### CODE REVIEW

File: src/core/document/query.pl [hunk 1]
```diff
@@ -141,13 +141,13 @@
...
         do_or_die(once(class_subsumed(DB, Type, Query_Type_Ex)),
-                  error(query_error(not_a_a_subclass(Type, Query_Type_Ex)), _))
+                  error(query_error(not_a_subclass(Type, Query_Type_Ex)), _))
     ;   var(Type)
     ->  throw(error(query_error(unknown_type_for_query(Query)), _))
     ;   Query_Type_Ex = Type),
 
     do_or_die(type_descriptor(DB, Query_Type_Ex, Query_Type_Descriptor),
-              error(query_error(type_not_found(Query_Type)), _)),
+              error(query_error(type_not_found(Query_Type_Ex)), _)),
```
Comment (spl) [inline src/core/document/query.pl:150]: I believe this changes `Blah` to `http://somewhere.for.now/schema#Blah` in the output of the test case below? If so, I think it's better to report the user input exactly, which is `Blah`. Otherwise, it adds extra cognitive load to try to match the error report with the input.

**Review by spl — CHANGES_REQUESTED** [review]
Looks find in general. Just one question to resolve.

File: src/core/document/query.pl (hunk 1 above)
Comment (GavinMendelGleason) [reply src/core/document/query.pl:150]: I agree, but there is actually no unexpanded type in the context at the moment. The `Query_Type` is unbound. To get the unprefixed type would require additional machinery.
