### PR TITLE
Diff error handler

### LINKED ISSUE #1391: Stack trace on CLI apply
```
gavin@titan:~/dev/terminusdb$ ./terminusdb apply admin/foo
  [19] split_string(_1416,:,'',_1422)
  [18] utils:split_atom(_1458,:,[_1466,_1472]) at /home/gavin/dev/terminusdb/src/core/util/utils.pl:450
  [17] data_version:read_data_version('<garbage_collected>','<garbage_collected>') at /home/gavin/dev/terminusdb/src/core/util/data_version.pl:47
  [16] api_patch:coerce_to_commit(branch_descriptor{branch_name:"main",repository_descriptor:repository_descriptor{database_descriptor: ...,repository_name:"local"}},_1550,_1552) at /home/gavin/dev/terminusdb/src/core/api/api_patch.pl:33
  [15] api_patch:api_apply_squash_commit('<garbage_collected>','terminusdb://system/data/User/admin','admin/foo',commit_info{author:admin,message:'cli: apply'},'<garbage_collected>',_1622,[type(squash),...|...]) at /home/gavin/dev/terminusdb/src/core/api/api_patch.pl:163
  [14] '<meta-call>'('<garbage_collected>') <foreign>
  [13] catch(cli:(...,...),error(apply_squash_witnesses(_1740)),cli:json_write(current_output,_1752)) at /home/gavin/.swivm/versions/v8.5.8/lib/swipl/boot/init.pl:562
  [12] catch(cli:catch(...,...,...),error(instantiation_error,context(...,_1812)),cli:do_or_die(...,...)) at /home/gavin/.swivm/versions/v8.5.8/lib/swipl/boot/init.pl:562
  [11] catch_with_backtrace(cli:catch(...,...,...),error(instantiation_error,context(...,_1884)),cli:do_or_die(...,...)) at /home/gavin/.swivm/versions/v8.5.8/lib/swipl/boot/init.pl:629
Error: instantiation_error
```

### PR DESCRIPTION
**Pull request by GavinMendelGleason**
Fixes #1391

### CODE REVIEW

File: src/core/api/api_error.pl [hunk 1]
```diff
@@ -201,7 +201,7 @@
     ->  Opening_Msg = "Remote authentication failed"
     ;   Opening_Msg = "Remote connection failed"
     ),
-
+    % Needs more options....
```
Comment (matko) [inline src/core/api/api_error.pl:204]: What is this comment about?

File: src/server/routes.pl [hunk 2]
```diff
@@ -2553,7 +2553,7 @@
     ),
 
     api_report_errors(
-        apply,
+        diff,
```
Comment (matko) [inline src/server/routes.pl:2556]: why did this change?

File: src/core/api/api_error.pl (hunk 1 above)
Comment (GavinMendelGleason) [reply src/core/api/api_error.pl:204]: Another bug :D This needs to capture more cases.
