### PR TITLE
Graphql backlinks

### LINKED ISSUE #1562: Collections do not work over concrete datatypes (xsd:)

### PR DESCRIPTION
**Pull request by GavinMendelGleason**
Fixes #1562 and introduces inverted frames

### CODE REVIEW

File: src/rust/terminusdb-community/src/graphql/schema.rs [hunk 1]
```diff
@@ -435,22 +481,56 @@ impl<'a, C: QueryableContextType + 'a> GraphQLType for TerminusType<'a, C> {
...
             TypeDefinition::Class(d) => Self::generate_class_type(d, info, registry),
             TypeDefinition::Enum(_) => panic!("no enum expected here"),
         }
     }
 }
 
+fn rewind_rdf_list<'a>(instance: &'a dyn Layer, cons_id: u64) -> Option<u64> {
+    if let Some(rdf_rest) = instance.predicate_id(RDF_REST) {
+        let mut cons = Some(cons_id);
+        while let Some(id) = cons {
```
Comment (matko) [inline src/rust/terminusdb-community/src/graphql/schema.rs:497]: this doesn't have to be a while let with a Some, cause you immediately return in the None case. so it could be a simple loop {}

File: src/rust/terminusdb-community/src/graphql/schema.rs [hunk 2]
```diff
@@ -435,22 +481,56 @@ impl<'a, C: QueryableContextType + 'a> GraphQLType for TerminusType<'a, C> {
...
+        cons
+    } else {
+        None
+    }
+}
+
+fn subject_has_type<'a>(instance: &'a dyn Layer, subject_id: u64, class: &str) -> bool {
+    if let Some(rdf_type_id) = instance.predicate_id(RDF_TYPE) {
+        if let Some(class_id) = instance.object_node_id(class) {
+            instance.triple_exists(subject_id, rdf_type_id, class_id)
```
Comment (matko) [inline src/rust/terminusdb-community/src/graphql/schema.rs:518]: if you return here you can save on two return falses by making it the default at the end.

File: src/rust/terminusdb-community/src/graphql/schema.rs [hunk 3]
```diff
@@ -471,123 +551,216 @@ impl<'a, C: QueryableContextType + 'a> GraphQLValue for TerminusType<'a, C> {
...
+                let domain_uri = allframes.fully_qualified_class_name(domain);
+                let field_id = instance.predicate_id(&property_expanded)?;
+                // List and array are special since they are *deep* objects
+                match kind {
+                    FieldKind::List => {
+                        let object_ids = instance
+                            .triples_o(self.id)
+                            .flat_map(|t| {
+                                instance
+                                    .predicate_id(RDF_FIRST)
```
Comment (matko) [inline src/rust/terminusdb-community/src/graphql/schema.rs:571]: do this lookup outside the flat_map cause it might get repeated too often

File: src/rust/terminusdb-community/src/graphql/schema.rs [hunk 4]
```diff
@@ -471,123 +551,216 @@ impl<'a, C: QueryableContextType + 'a> GraphQLValue for TerminusType<'a, C> {
...
+                                    .filter(|rdf_first| t.predicate == *rdf_first)
+                                    .map(|_| t.subject)
+                            })
+                            .flat_map(|cons| rewind_rdf_list(instance, cons))
```
Comment (matko) [inline src/rust/terminusdb-community/src/graphql/schema.rs:575]: should this be a flat_map? why is rewind_rdf_list returning an iterator?

Comment (matko) [reply src/rust/terminusdb-community/src/graphql/schema.rs:575]: rewind_rdf_list returns an option, so flat_map gets rid of that.

**Review by matko — DISMISSED** [review]
some small comments, i could be talked out of their necessity.

**Review by matko — APPROVED** [review]
